### ISSUE TITLE
View Profile Page

### ISSUE THREAD

**Issue by cameronjtoy** [cse442-at-ub/project_s23-webarebears#15]
Task Acceptance Tests

Test 1: Viewing account

Go to: https://www.figma.com/proto/rPiZN9ngnq5XSznHMWE7oO/Room8?node-id=8%3A761&scaling=scale-down&page-id=0%3A1&starting-point-node-id=8%3A663

Click on the profile picture to navigate towards the profile page.

Expected Outcome: You will be navigated towards your profile page where you have multiple options that will pop up: 

- Edit Profile - pop up to change your profile picture
- Completed Debts - History of debts owed that have been fulfilled
- Completed Tasks - History of Tasks that have been fulfilled
- Pending Tasks - Current Tasks that have not been fulfilled
- Pending Debts - Current debts that have not been fulfilled
- Help & Support 
- Terms and Condition
- About Us
- Feedback

**Comment by eshanub** [comment]
What should display on the screen when you navigate to profile page? Clarify this and i can close the issue once I can see the expected behavior.
