### ISSUE TITLE
As a registered user, I would like to see notifications if I was assigned a task or a bill from a group.

### ISSUE THREAD

**Issue by JasonMai11** [cse442-at-ub/project_s23-webarebears#42]
**Acceptance Test:**

*Test 1*
a) Go to https://www.figma.com/file/rPiZN9ngnq5XSznHMWE7oO/Room8?node-id=8%3A737&t=zeC1zuwvgKjqrxFa-0
b) From the Home Page, click on the notification button.

Expected Outcome: You should should see the tasks that you was assigned or a bill from a group.

*Test 2*
a) Go to https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442ac/backend/login.php
b) Register/login(You will need two accounts for this)
c) On one of the accounts, navigate to the Messages Page, then click on "Add Friend" and search for your other account and click on add friend.
d) Navigate to the Messages Page, then click on "Create Group".
e)Enter the group name and select your other account name. Then click on "Create".
f) You should see the group name on the Messages page. Click on the group name and click on "Set Task". Then choose your other account to assign task to.
g) On the Task Description, type in the task description.
h) Select the Due Date. And click on "Create Task".
i) You should see the group messages again. Click on Divide Bills
j) Select your other account to divide the bills.
k) On the Bill Description field, type in the reason for splitting the bills.
l) Type in the total amount on the "Total Amount" field.
m) Select a due date and click on "Divide Bills"
n) Click on log out and log in to your other account
o) On the home page, click on the notification button.

Expected Outcome: You should see the Task you were assigned and bills from your other account.

**Comment by eshanub** [comment]
You need to add acceptance tests and label as such.
