### ISSUE TITLE
Style search bar so that the result is a drop down content

### ISSUE THREAD

**Issue by Junstinr** [cse442-at-ub/project_s23-webarebears#46]
**Task Test**

__Test 1__
a) Go to https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442ac/backend/login.php
b) Login using username: abc123 password:abc123!
c) From the application, navigate to any page and use the search bar to search up a username. Account that exist: Junstin
d) If the username exist, it should be display below the search bar and you should be able to add them as friend.
e) If the username does not exist, it should display a message saying "No results found."

**Comment by eshanub** [comment]
Label as task test and add task tests

**Comment by eshanub** [comment]
This should be moved to complete by now, you have demo'd it to me
