### ISSUE TITLE
As a registered user, I would like use a search bar to find friends from the home page.

### ISSUE THREAD

**Issue by cameronjtoy** [cse442-at-ub/project_s23-webarebears#55]
**Acceptance Test**

Test 1

a) Go to https://www.figma.com/file/rPiZN9ngnq5XSznHMWE7oO/Room8?node-id=8%3A737&t=zeC1zuwvgKjqrxFa-0
b) login/register
c) On the Home page, use the search bar to search for users

Expected Outcome:
You should see the users below the search bar.

Test 2

a) Go to  https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442ac/backend/login.php
b) Log in using - Username: abc123 Password: abc123!
c)On the Home Page, use the search bar to loop up "Junstin"

Expected Outcome: An account with the username "Junstin" should pop up below the search bar.

**Comment by eshanub** [comment]
Create task tests for this
