### ISSUE TITLE
As a registered user, I want to change my password easily and securely, with clear instructions.

### ISSUE THREAD

**Issue by cameronjtoy** [cse442-at-ub/project_s23-webarebears#56]
**Acceptance Test**

*Test 1*

a) Go to https://www.figma.com/file/rPiZN9ngnq5XSznHMWE7oO/Room8?node-id=8%3A737&t=zeC1zuwvgKjqrxFa-0
b) Login/register
c) From the Home page, click on the profile icon. You should be taken to the Profile Page
d) Click on "Settings"
e) Click on the new password

Expected Outcome: you should have a new password

*Test 2*

a) Go to https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-b42ac/backend/login.php
2) Login using Username: testing Password: password123
c) From the Home Page, click on the profile icon. This should take you to the Profile Page.
e) Click on "Settings"
f) On the New Password Field, type in your new password: "newpassword123"
g) Then click on "Change password" and confirm your changed password.
h) Click on "Back to Profile" and scroll down and click on "Logout"
i) You should be taken back to the login page. Type your username and your new password. Username: testing Password: newpassword123

Expected Outcome: You should be able to login using your new password.

**Comment by eshanub** [comment]
Create acceptance tests for this
