### ISSUE TITLE
As a roommate, I would like to be able to use a bill calculator so that I can divide the bill with my group members

### ISSUE THREAD

**Issue by lyao4321** [cse442-at-ub/project_s23-webarebears#6]
**Acceptance Tests**
a)Go to https://www.figma.com/file/rPiZN9ngnq5XSznHMWE7oO/Room8?node-id=8%3A737&t=zeC1zuwvgKjqrxFa-0
b)Click the Divide Bill button and divide the bill between the users in the group. You will be allowed to set the price of the bill, provide context, and choose who to divide the bill amongst. c)The user should be able to enter the bill and a message will appear notifying those who owe money to the user. Once all these steps are complete and you hit submit, you should be take to the message page again seeing those who owe the user.

Expected Outcome Adding Funds: The user should be able to add the number of funds another user owes by clicking a button.
Expected Outcome Removing Funds: Once the debted user has paid another user, the fund should decrease on the total balance.
Expected Outcome Personal to User: Each user should have their ow personalized funds where they can not see the total debt of others.

*Test 1*

a) Go to https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442ac/backend/login.php
b) Login/Register an account
c) From the Home Page, navigate to the Messages Section. 
d) From the Messages Section (Add Friends if necessary), you should click Divide bills
e) Select the users that you would like to divide the bill with. (Use another account to divide the bill with)
f) Then log out of the current account and log in to the account with which you divided the bill. 
g) Navigate to the Balance Section and check that the user has a new debt balance added.

Expected Outcome: Debt should be added to the assigned debt user. Should be seen in the Balance Section

**Comment by eshanub** [comment]
Label as "Acceptance Tests" & provide a test account for the user to use during login. Make sure you update your descriptions with this.
