### ISSUE TITLE
Change Password of Current User

### ISSUE THREAD

**Issue by cameronjtoy** [cse442-at-ub/project_s23-webarebears#61]
**Task Test**

*Test 1*
a) Go to https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442ac/backend/home.php
b) Login using username: abc123 password:abc123!
c) Navigate to the Profile Page. 
d) Then click on "Settings" and on the New Password field, type in a new password:abc123456!. 
e) Then click on "Change Password" and confirm the changes. 
f) Then click on "Back to profile" and click on "Log Out".
g) User should be able to log in using their new password.

**Comment by eshanub** [comment]
Label as task test
