### ISSUE TITLE
Fix the front-end for viewing pending friend requests as well as managing the friends list display.

### ISSUE THREAD

**Issue by Junstinr** [cse442-at-ub/project_s23-webarebears#66]
**Task Test**

*Test 1*
a) Go to https://www.figma.com/file/rPiZN9ngnq5XSznHMWE7oO/Room8?node-id=8%3A737&t=zeC1zuwvgKjqrxFa-0
b) Navigate to the Messages page, then click on Add Friend button on the Figma. 
c) Go to https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442ac/backend/home.php
d) Login using username: abc123 password:abc123!
e) Navigate to the Messages page and click on Add Friend button.

Expected Outcome: The styling from application for the Add Friend page should match the styling for the Figma.

**Comment by eshanub** [comment]
Label as task test
