### ISSUE TITLE
Profile Picture Backend

### ISSUE THREAD

**Issue by cameronjtoy** [cse442-at-ub/project_s23-webarebears#83]
Task Tests

Test 1:
a)Go to https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442ac/backend/login.php
b)login to the test account(username:abc123, password:abc123)
c)click on the profile picture icon at the top left of the page
d) You will be navigated to the profile page
e) On the profile tab, click on the picture icon
f) Choose a small picture that can be used for a profile picture
g) Insert the picture
h)Confirm that the profile picture has changed to the correct image

Test 2:
a)Follow all the steps of Test 1.
b) Navigate to all pages within the application and check the profile picture.
c) Confirm that the profile picture is the newly updated image.

**Comment by eshanub** [comment]
Move to in progress->testing. This also has no dependencies
