### ISSUE TITLE
Create a option to change colors in the create group section

### ISSUE THREAD

**Issue by lyao4321** [cse442-at-ub/project_s23-webarebears#90]
**Task Tests**

_Test 1_
a)Go to https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442ac/backend/login.php
b)login to the test account(username:abc123, password:abc123!)
c)You will be navigated to the home page
d)Navigate to the messages pages through the navbar.
e) Click the create group button
f) Confirm that there is a section that is for picking a group color

_Test 2:_
a) Follow all the steps from test 1
b) Click the color box
c) Confirm that a menu opens up with different color options

_Test 3:_
a) Follow all the steps from test 1 and 2.
b) Click a color that is different from the current color
c) Confirm that the color box is changed to the new color

**Comment by eshanub** [comment]
move to in progress -> testing

**Comment by eshanub** [comment]
No dependencies
